# Generated by Django 4.2.4 on 2023-08-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0005_remove_destination_thing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='destination',
        ),
        migrations.AddField(
            model_name='profile',
            name='destinations',
            field=models.ManyToManyField(to='passes.destination'),
        ),
    ]
