# Generated by Django 4.2.4 on 2023-08-02 17:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passes', '0006_remove_profile_destination_profile_destinations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='HallPass',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
