# Generated by Django 4.2.4 on 2023-08-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0012_student_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='text_color',
            field=models.CharField(default='', max_length=7),
        ),
    ]
