# Generated by Django 4.2.5 on 2023-09-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0013_category_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallpass',
            name='Arrival_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hallpass',
            name='Cancel_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
