# Generated by Django 4.2.5 on 2023-09-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0015_alter_hallpass_time_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallpass',
            name='Cancel_time',
        ),
        migrations.AlterField(
            model_name='hallpass',
            name='Time_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
