# Generated by Django 4.2.5 on 2023-09-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0017_hallpass_forgot_time_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hallpass',
            old_name='Arrival_time',
            new_name='arrival_time',
        ),
        migrations.RenameField(
            model_name='hallpass',
            old_name='Time_in',
            new_name='time_in',
        ),
        migrations.RenameField(
            model_name='hallpass',
            old_name='Time_out',
            new_name='time_out',
        ),
    ]
